/* Seoteuk Mate v3.8.2 - area-specific student record evaluator */
(function(){'use strict';if(window.__SM381_EVALUATOR__)return;window.__SM381_EVALUATOR__=1;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),B=t=>window.calculateNeisBytes?.(String(t||''))??new TextEncoder().encode(String(t||'')).length;
const AREA={course:{label:'교과세특',max:1500},auto:{label:'자율·자치활동',max:1500},club:{label:'동아리활동',max:1500},career:{label:'진로활동',max:1500},behavior:{label:'행동특성·종합의견',max:900}};
const MAP={'교과세특':'course','교과':'course','자율활동':'auto','자율·자치활동':'auto','자율':'auto','동아리활동':'club','동아리':'club','진로활동':'career','진로':'career','행동특성':'behavior','행동특성·종합의견':'behavior','행발':'behavior'};
const RX={action:/작성|제작|발표|토론|비교|분석|조사|검토|설명|질문|기획|참여|구성|수정|해석|조율|제안|선정|탐색|확인|적용|계산|관찰|분류|재구성|설계/g,evidence:/자료|사료|기사|도서|통계|그래프|표|모형|보고서|산출물|작품|기록|초고|수정본|설문|도면|발표자료|활동지/g,inquiry:/의문|질문|가설|비교|분석|원인|조건|관계|한계|반례|전제|왜|어떻게|검증/g,logic:/때문|따라|반면|그러나|따라서|관계|영향|조건|원인|결과|근거|전제|반례/g,feedback:/피드백|수정|보완|고쳐|정정|재검토|다시|반영|초기|처음|이후|반론/g,growth:/성장|확장|심화|구체화|이해함|깨달|관점|후속|다음|변화|발전|계획/g,collab:/협력|모둠|조율|경청|소통|공유|동료|친구|의견|합의|배려|공동/g,role:/역할|담당|맡아|주도|제안|기획|운영|정리|관리/g,problem:/문제|해결|개선|수정|대안|병목|갈등|조정|오류|원인|재시도/g,career:/진로|전공|직무|학과|분야|직업|관심|탐색|계획|역량/g,responsibility:/책임|기한|성실|자기관리|관리|완료|마무리|준수|꾸준/g,reflection:/성찰|한계|부족|점검|되돌아|재검토|확인|범위|불확실/g,praise:/탁월|우수|뛰어|최고|완벽|압도|전문가 수준|돋보임/g};
const STOP=new Set('학생 활동 수업 과정 탐구 통해 관련 대한 내용 자료 교과 학습 참여 작성 수행 이해 확인 결과 중심 바탕 활용 보임 있음 해당 실제 자신의 하고 하며 함'.split(' '));
function areaKey(v){return AREA[v]?v:(MAP[String(v||'').trim()]||'course')}function cnt(rx,t){const r=new RegExp(rx.source,rx.flags);return (String(t||'').match(r)||[]).length}function f(rx,t,target=3){return Math.min(1,cnt(rx,t)/target)}
function toks(t){return new Set((String(t||'').match(/[가-힣A-Za-z0-9]{2,}/g)||[]).map(x=>x.toLowerCase()).filter(x=>!STOP.has(x)))}function overlap(a,b){const A=toks(a),E=toks(b);if(!A.size||!E.size)return 0;let n=0;A.forEach(x=>E.has(x)&&n++);return n/Math.max(1,Math.min(A.size,E.size))}
const SUBJ={'물리학':/힘|운동|에너지|파동|전기|자기|하중|평형|벡터|속도|가속도/,'화학':/반응|산|염기|평형|농도|몰|분자|결합|완충|산화|환원/,'생명과학':/세포|유전자|발현|항상성|신경|생태|효소|단백질|진화|유전/,'수학':/함수|그래프|확률|통계|미분|적분|좌표|수열|벡터|모델|변화율/,'확률과\\s*통계':/확률|통계|표본|분포|평균|분산|조건부|비율|유병률|예측도/,'문학':/작품|서술|화자|인물|구절|상징|비평|서사|시점|표현/,'언어와\\s*매체':/기사|매체|제목|인용|독자|편집|프레이밍|표현|정보/,'한국사':/사료|시대|사건|인물|정책|운동|역사|맥락|전개/,'세계사':/사료|시대|제국|혁명|전쟁|교류|역사|맥락/,'지구과학':/기후|대기|해양|지질|지진|천체|일사|열섬|지표|바람/};
function subjectFit(subject,text){const s=String(subject||'').trim();if(!s)return .72;for(const [k,rx] of Object.entries(SUBJ))if(new RegExp(k).test(s))return Math.min(1,.45+f(rx,text,3)*.55);return Math.min(1,.55+f(/개념|원리|자료|단원|수업|학습|문제|해석|적용/g,text,4)*.45)}
function expressionFactor(text,max){const b=B(text),density=b/max;let v=density<.35?.45:density<.6?.65:density<=1?.95:.2;v-=Math.min(.45,cnt(RX.praise,text)*.12);return Math.max(0,Math.min(1,v))}
function metric(arr,name,weight,value,tip){arr.push({name,weight,value:Math.max(0,Math.min(1,value)),score:Math.round(weight*Math.max(0,Math.min(1,value))),tip})}
function evaluate(opts={}){const area=areaKey(opts.area),cfg=AREA[area],text=String(opts.text||'').trim(),evidence=String(opts.evidence||'').trim(),subject=String(opts.subject||'').trim(),m=[];const A=f(RX.action,text,6),E=f(RX.evidence,text,4),Q=f(RX.inquiry,text,5),L=f(RX.logic,text,5),F=f(RX.feedback,text,4),G=f(RX.growth,text,4),C=f(RX.collab,text,4),R=f(RX.role,text,4),P=f(RX.problem,text,4),V=f(RX.career,text,4),D=f(RX.responsibility,text,4),H=f(RX.reflection,text,3),X=expressionFactor(text,cfg.max);
if(area==='course'){metric(m,'구체적 행동 근거',20,A*.65+E*.35,'실제 학생의 행동과 산출물을 더 구체적으로 제시');metric(m,'탐구 깊이',20,Q*.7+H*.3,'질문·비교·한계·반례가 드러나는 탐구 흐름 보강');metric(m,'사고·인과 구조',15,L,'조건·원인·근거와 결론의 연결을 명확히 제시');metric(m,'피드백·수정',15,F,'초기 판단과 피드백 후 수정 장면 보강');metric(m,'교과 적합성',15,subjectFit(subject,text),'과목 고유 개념과 사고 방식을 더 분명히 연결');metric(m,'성장·확장',10,G,'후속 질문 또는 관점 변화 보강');metric(m,'표현·밀도',5,X,'추상 칭찬을 줄이고 실제 근거 밀도를 높임')}
else if(area==='auto'){metric(m,'실제 역할·주도성',20,R*.55+A*.45,'학생이 맡아 한 행동을 구체화');metric(m,'공동체 참여',15,A*.45+C*.55,'참여가 공동체에 미친 맥락을 제시');metric(m,'협력·소통',15,C,'조율·경청·합의 장면 보강');metric(m,'문제 해결·개선',20,P*.65+L*.35,'문제 발견-대안-수정 흐름 보강');metric(m,'변화·성장',15,F*.4+G*.6,'활동 전후의 판단 변화 제시');metric(m,'구체성·근거',10,E*.45+A*.55,'관찰 가능한 근거와 결과물 제시');metric(m,'표현·밀도',5,X,'추상적 미사여구보다 실제 행동 중심으로 조정')}
else if(area==='club'){metric(m,'활동·역할 구체성',15,R*.45+A*.55,'동아리에서 실제 수행한 역할을 명확히 제시');metric(m,'탐구·제작 과정',20,A*.45+Q*.55,'과정에서의 질문·비교·검토를 보강');metric(m,'산출물·근거',15,E,'산출물과 확인 가능한 근거 제시');metric(m,'협업·피드백',15,C*.55+F*.45,'동료 피드백과 수정 장면 제시');metric(m,'관심 심화',15,G*.55+Q*.45,'활동이 다음 탐구로 이어지는 흐름 제시');metric(m,'문제 해결',15,P*.6+H*.4,'오류·한계 발견과 개선 과정을 제시');metric(m,'표현·밀도',5,X,'나열보다 과정 중심으로 압축')}
else if(area==='career'){metric(m,'진로 탐색 구체성',15,V*.5+A*.5,'실제 탐색 활동을 구체적으로 제시');metric(m,'학생의 실제 노력',20,A*.65+E*.35,'조사·비교·발표 등 학생 행동 근거 보강');metric(m,'이해·통찰',20,Q*.35+L*.4+H*.25,'직무·학문에 대한 이해가 어떻게 달라졌는지 제시');metric(m,'생각·계획의 변화',15,F*.45+G*.55,'막연한 관심에서 구체적 판단으로 변화한 지점 제시');metric(m,'후속 계획',15,G*.55+V*.45,'다음 학습·탐구 계획을 구체화');metric(m,'교과·활동 연결',10,E*.35+L*.3+V*.35,'진로를 억지로 붙이지 말고 실제 경험과 연결');metric(m,'표현·밀도',5,X,'진로명 반복보다 탐색 과정 중심으로 작성')}
else{metric(m,'지속 관찰 행동',20,A*.45+D*.3+H*.25,'일회성 미담보다 반복 관찰된 행동을 제시');metric(m,'학습 태도',15,A*.55+H*.45,'학습 상황에서의 구체적 태도를 보강');metric(m,'책임감·자기관리',15,D,'기한·역할·자기관리 행동을 제시');metric(m,'배려·협력·소통',15,C,'상대 존중과 협력의 구체 장면을 제시');metric(m,'문제 상황 대응',10,P*.65+H*.35,'문제 발생 후 대응·수정 과정을 제시');metric(m,'성장·변화',15,F*.35+G*.65,'학년 또는 활동 반복 속 변화가 드러나게 작성');metric(m,'구체성',5,E*.4+A*.6,'추상적 성격평가보다 관찰 행동을 제시');metric(m,'표현·밀도',5,X,'다른 영역 내용을 옮겨 적지 말고 종합적으로 압축')}
const score=Math.max(0,Math.min(100,m.reduce((n,x)=>n+x.score,0))),grade=score>=90?'A':score>=80?'B':'C',bytes=B(text),official=window.scanOfficial2026?.(text)||[],risks=[];if(!text)risks.push('본문이 비어 있음');if(bytes>cfg.max)risks.push('최대 바이트 초과: '+bytes+'/'+cfg.max+'B');if(cnt(RX.praise,text))risks.push('추상 평가어가 감지됨 — 실제 행동 근거와 직접 연결 필요');official.slice(0,5).forEach(x=>risks.push((x.severity==='hard'?'기재 주의: ':'확인 필요: ')+(x.title||x.why||x.match||'공식 기재요령 점검')));
let evidenceMatch=null,unsupported=[];if(evidence){const ov=overlap(text,evidence),claims=(text.match(/\d+(?:\.\d+)?%?|수상|입상|1위|팀장|회장|논문|설문|실험|인터뷰|발표|제작|주도/g)||[]);unsupported=[...new Set(claims.filter(x=>!evidence.includes(x.replace(/\d+(?:\.\d+)?%?/,'').trim())&&!/\d/.test(x)?true:/\d/.test(x)&&!evidence.includes(x)))];evidenceMatch=Math.max(0,Math.min(100,Math.round(55+ov*45-unsupported.length*8)));if(evidenceMatch<65)risks.push('원자료와 본문의 어휘·행동 일치도가 낮음');if(unsupported.length)risks.push('원자료에서 직접 확인이 필요한 주장: '+unsupported.slice(0,6).join(', '))}else risks.push('원자료 미입력 — 문장 완성도만 평가하며 사실성 평가는 제외');
const sorted=[...m].sort((a,b)=>b.value-a.value),strengths=sorted.slice(0,2).map(x=>x.name+' '+x.score+'/'+x.weight),low=[...m].sort((a,b)=>a.value-b.value).slice(0,3),improvements=low.map(x=>x.tip);return{area,label:cfg.label,subject,text,evidence,score,grade,bytes,max:cfg.max,criteria:m,strengths,improvements,risks,evidenceMatch,unsupported}}
window.SeoteukEvaluator38={evaluate,areaKey,AREA};window.evaluateRecord38=function(opts){return evaluate(opts)};
window.__SEOTEUK_EVALUATOR_LITE__=true;
})();
