import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),pkg=JSON.parse(read('package.json')),VERSION=pkg.version;
assert.equal(VERSION,'3.8.2');const required=['index.html','evidence-fusion.js','student-workspace.js','analytics-dashboard.js','local-tools-admissions.js','teacher-ux.js','editor-live-inspector.js','student-record-suite-v36.js','record-writers-v36.js','record-evaluator-v38.js','bulk-activity-engine-v38.js','portfolio-evaluator-v382.js','student-portfolio-v37.js','demo-students-v37.js','ui-mode-v37.js','teacher-workflow-v38.js','firebase-cloud.js','official-2026.js','sw.js','vercel.json','package.json','vendor/tailwind.js','vendor/xlsx.full.min.js','vendor/pdf.min.js','vendor/pdf.worker.min.js'];
for(const p of required)assert.ok(exists(p),`missing: ${p}`);assert.match(read('VERSION.txt'),/v3\.8\.2/);const index=read('index.html');assert.ok(index.includes('v3.8.2'));
for(const p of ['evidence-fusion','teacher-ux','student-record-suite-v36','record-writers-v36','record-evaluator-v38','bulk-activity-engine-v38','portfolio-evaluator-v382','ui-mode-v37','editor-live-inspector'])assert.ok(index.includes(`./${p}.js?v=3.8.2`),`cache-buster mismatch: ${p}`);
const progress=read('evidence-fusion.js'),writers=read('record-writers-v36.js'),evaluator=read('record-evaluator-v38.js'),bulk=read('bulk-activity-engine-v38.js'),portfolio=read('portfolio-evaluator-v382.js'),demo=read('demo-students-v37.js'),ui=read('ui-mode-v37.js'),sw=read('sw.js'),teacher=read('teacher-ux.js'),live=read('editor-live-inspector.js');
for(const x of ['① 분석','② 준비','③ 생성','④ 검증','⑤ 완료','progressStage','generateThreeCandidates','generateFromSubjectWriter'])assert.ok(progress.includes(x),`visual progress missing: ${x}`);
assert.ok(writers.includes('syncCourseSubject')&&writers.includes('SeoteukProgress')&&writers.includes('로컬 초안 생성'),'writer subject/progress missing');assert.ok(evaluator.includes('개선본 생성 완료')&&evaluator.includes('원본·개선본 비교')&&evaluator.includes('__SM381_LAST_IMPROVEMENT'),'improvement visibility missing');
assert.ok(bulk.includes('스마트 열 매핑')&&bulk.includes('inferColumnMap')&&bulk.includes('runQualityPipeline38')&&bulk.includes('qualityHistory'),'smart mapping/quality pipeline missing');assert.ok(portfolio.includes('학생부 전체 평가')&&portfolio.includes('careerLink')&&portfolio.includes('growthScore'),'whole-record evaluation missing');assert.ok(ui.includes('학생부 전체평가')&&ui.includes('여러 활동 Excel'),'beginner quick actions missing');
assert.ok(sw.includes('seoteukmate-v382-')&&sw.includes("'./portfolio-evaluator-v382.js'"),'PWA cache missing v3.8.2 module');assert.ok(teacher.includes("const VERSION='3.8.2'")&&live.includes("const VERSION='3.8.2'"),'visible version mismatch');
const elements={};function el(value=''){return{value,innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){},contains(){return false}},prepend(x){this.prepended=x},appendChild(){},querySelector(){return null},querySelectorAll(){return[]}}}
globalThis.window={scanOfficial2026:()=>[],subjectList:['한국사','물리학','문학']};globalThis.document={readyState:'loading',addEventListener:()=>{},getElementById:id=>elements[id]||null,createElement:()=>el(),body:el()};globalThis.setTimeout=()=>{};globalThis.MutationObserver=class{observe(){}};globalThis.localStorage={getItem:()=>null,setItem:()=>{}};
eval(evaluator);elements['sm38e-area']=el('course');elements['sm38e-subject']=el('한국사');elements['sm38e-text']=el('사료를 비교함.');elements['sm38e-evidence']=el('두 사료의 작성 주체와 목적을 비교하고 기사 초고를 작성함. 피드백 후 과장 표현을 수정하고 결론 범위를 좁힘. 반례를 검토해 후속 질문을 제안함.');elements['sm38e-result']=el();window.SeoteukProgress={start(){},set(){},done(){},fail(){}};window.showToast=()=>{};const improved='서로 다른 사료의 작성 주체와 목적을 비교하여 기사 초고를 작성함. 피드백에서 과장된 표현을 지적받은 뒤 자료가 뒷받침하는 범위로 문장을 수정하고 결론의 범위를 좁힘. 토론에서 제시된 반례를 다시 검토하여 자신의 해석을 조정하고 후속 질문을 제안함.';window.requestAI=async()=>improved;const before=window.runRecordEvaluation38();await window.improveEvaluatedRecord38();assert.equal(elements['sm38e-text'].value,improved);assert.ok(window.__SM381_LAST_IMPROVEMENT&&window.__SM381_LAST_IMPROVEMENT.after.score>=before.score,'improvement generation/re-evaluation failed');window.restoreImprovementOriginal38();assert.equal(elements['sm38e-text'].value,'사료를 비교함.','original restore failed');
eval(demo);eval(portfolio);const s=window.__SM_DEMO_STUDENTS_371[0],rec={appState:{subjectData:{}},categoryDrafts:{자율활동:{full:{v1:'',v2:'',v3:''}},동아리활동:{full:{v1:'',v2:'',v3:''}},진로활동:{full:{v1:'',v2:'',v3:''}}},behaviorDrafts:{full:{v1:'',v2:'',v3:''}}};for(const r of s.records){if(r.k==='course')rec.appState.subjectData[r.sub]={full:{v1:'',v2:'',v3:r.final}};else if(r.k==='auto')rec.categoryDrafts.자율활동.full.v3=r.final;else if(r.k==='club')rec.categoryDrafts.동아리활동.full.v3=r.final;else if(r.k==='career')rec.categoryDrafts.진로활동.full.v3=r.final;else rec.behaviorDrafts.full.v3=r.final}const pa=window.SeoteukPortfolioEvaluator382.analyze({id:'demo',no:'1',name:'김서준',career:'건축공학과'},rec);assert.equal(pa.rows.length,7);assert.equal(pa.completeness,100);assert.equal(pa.missing.length,0);
eval(bulk);const messy=[{번호:'20101',학생:'홍길동',기록영역:'교과세특',교과명:'한국사',프로젝트:'역사신문',담당역할:'사료검토',실행메모:'두 사료의 주체와 목적을 비교함',결과자료:'기사초고',수정사항:'과장 표현을 수정함',활동후변화:'사실과 해석을 구분함',희망계열:'역사학'},{번호:'20101',학생:'홍길동',기록영역:'교과세특',교과명:'한국사',프로젝트:'토론',담당역할:'발표',실행메모:'다른 관점의 사료로 반론함',결과자료:'발표자료',수정사항:'결론 범위를 좁힘',활동후변화:'반례 검토가 강화됨',희망계열:'역사학'},{번호:'20101',학생:'홍길동',기록영역:'진로활동',교과명:'',프로젝트:'학과탐색',담당역할:'조사',실행메모:'교육과정을 비교함',결과자료:'보고서',수정사항:'관심을 연구질문으로 바꿈',활동후변화:'진로 구체화',희망계열:'역사학'}];const gs=window.SeoteukActivityBulk38.loadRows(messy,''),mp=window.SeoteukActivityBulk38.getMapping();assert.equal(mp.map.name,'학생');assert.equal(mp.map.subject,'교과명');assert.equal(mp.map.observation,'실행메모');assert.equal(gs.length,2);assert.equal(gs.find(g=>g.area==='course').rows.length,2);
const liveGroups=window.SeoteukActivityBulk38.getLiveGroups(),cg=liveGroups.find(g=>g.area==='course');cg.result='사료를 비교함.';cg.evaluation=window.SeoteukEvaluator38.evaluate({area:'course',subject:'한국사',text:cg.result,evidence:'두 사료의 주체와 목적을 비교함. 과장 표현을 수정함. 다른 관점의 사료로 반론함. 결론 범위를 좁힘.'});cg.qualityHistory=[{round:0,score:cg.evaluation.score,grade:cg.evaluation.grade,evidence:cg.evaluation.evidenceMatch,accepted:true}];elements['sm38a-target']=el('80');elements['sm38a-rounds']=el('1');window.requestAI=async()=>improved;await window.runQualityPipeline38();assert.ok(cg.qualityHistory.length>=2,'quality pipeline did not record a round');
for(const bad of ['<<<<<<<','=======\n','>>>>>>>'])for(const p of required)assert.ok(!read(p).includes(bad),`merge marker: ${p}`);console.log('SMOKE PASS',VERSION,'VISUAL PROGRESS + SMART MAPPING + WHOLE RECORD + EVIDENCE-LOCKED QUALITY PIPELINE');