import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),pkg=JSON.parse(read('package.json')),VERSION=pkg.version;
assert.equal(VERSION,'3.8.1');const required=['index.html','evidence-fusion.js','student-workspace.js','analytics-dashboard.js','local-tools-admissions.js','teacher-ux.js','editor-live-inspector.js','student-record-suite-v36.js','record-writers-v36.js','record-evaluator-v38.js','bulk-activity-engine-v38.js','student-portfolio-v37.js','demo-students-v37.js','ui-mode-v37.js','teacher-workflow-v38.js','firebase-cloud.js','official-2026.js','sw.js','vercel.json','package.json','vendor/tailwind.js','vendor/xlsx.full.min.js','vendor/pdf.min.js','vendor/pdf.worker.min.js'];
for(const p of required)assert.ok(exists(p),`missing: ${p}`);assert.match(read('VERSION.txt'),/v3\.8\.1/);const index=read('index.html');assert.ok(index.includes('v3.8.1'));
for(const p of ['teacher-ux','student-record-suite-v36','record-writers-v36','record-evaluator-v38','bulk-activity-engine-v38','demo-students-v37','ui-mode-v37','editor-live-inspector'])assert.ok(index.includes(`./${p}.js?v=3.8.1`),`cache-buster mismatch: ${p}`);
const writers=read('record-writers-v36.js'),evaluator=read('record-evaluator-v38.js'),bulk=read('bulk-activity-engine-v38.js'),demo=read('demo-students-v37.js'),ui=read('ui-mode-v37.js'),ws=read('student-workspace.js'),sw=read('sw.js'),teacher=read('teacher-ux.js'),live=read('editor-live-inspector.js');
assert.ok(writers.includes('syncCourseSubject')&&writers.includes("if(active==='course')syncCourseSubject(cur().f)"),'course subject sync missing');assert.ok(writers.includes('prefillRecordWriter36')&&writers.includes('SeoteukWriter36'),'writer APIs missing');
assert.ok(evaluator.includes('100점+A/B/C')&&evaluator.includes('evidenceMatch')&&evaluator.includes('improveEvaluatedRecord38'),'evaluator UX/features missing');for(const area of ['교과세특','자율·자치활동','동아리활동','진로활동','행동특성·종합의견'])assert.ok(evaluator.includes(area),`evaluator area missing: ${area}`);
assert.ok(bulk.includes('학생+영역+과목별')&&bulk.includes('usedIds')&&bulk.includes('regenerateLowActivity38')&&bulk.includes('saveActivityGroups38'),'multi-activity bulk features missing');assert.ok(ui.includes('기존 기록 평가')&&ui.includes('여러 활동 Excel'),'beginner quick actions missing');
assert.ok(ws.includes('behaviorDrafts')&&ws.includes('openStudentPortfolio37'),'workspace persistence missing');assert.ok(sw.includes('seoteukmate-v381-')&&sw.includes("'./record-evaluator-v38.js'")&&sw.includes("'./bulk-activity-engine-v38.js'"),'PWA cache missing new modules');
globalThis.window={};globalThis.document={readyState:'loading',addEventListener:()=>{},getElementById:()=>null};globalThis.setTimeout=()=>{};globalThis.localStorage={getItem:()=>null,setItem:()=>{}};eval(evaluator);const e1=window.SeoteukEvaluator38.evaluate({area:'course',subject:'한국사',text:'서로 다른 사료의 작성 주체와 목적을 비교하고 근거가 부족한 표현을 수정함. 동료의 반론을 확인한 뒤 결론 범위를 조정하고 후속 질문을 제안함.',evidence:'사료 비교표 작성, 기사 초고의 과장 표현을 수정하고 토론 뒤 결론을 고침.'});assert.ok(e1.score>=0&&e1.score<=100&&['A','B','C'].includes(e1.grade)&&e1.evidenceMatch!==null,'evaluator runtime failed');
eval(bulk);const gs=window.SeoteukActivityBulk38.loadRows([{학번:'1',이름:'홍길동',영역:'교과세특',과목:'한국사',활동명:'신문',관찰기록:'사료 비교',피드백:'표현 수정'},{학번:'1',이름:'홍길동',영역:'교과세특',과목:'한국사',활동명:'토론',관찰기록:'반론 제시',성장:'결론 조정'},{학번:'1',이름:'홍길동',영역:'진로활동',활동명:'학과탐색',관찰기록:'교육과정 비교'},{학번:'2',이름:'김하늘',영역:'자율',활동명:'행사',관찰기록:'역할 조율'}],'');assert.equal(gs.length,3);assert.equal(gs.find(g=>g.area==='course').rows.length,2,'same student/course activities not grouped');
eval(demo);const D=window.__SM_DEMO_STUDENTS_371;assert.equal(D.length,3);assert.deepEqual(D.map(x=>x.m),['건축공학과','국어국문학과','의예과']);for(const s of D){assert.equal(s.records.length,7);for(const r of s.records){const b=Buffer.byteLength(r.final,'utf8'),max=r.k==='behavior'?900:1500,min=r.k==='behavior'?840:1400;assert.ok(b>=min&&b<=max,`${s.m} ${r.k} byte density ${b}/${max}`)}}
assert.ok(teacher.includes("const VERSION='3.8.1'")&&live.includes("const VERSION='3.8.1'"));for(const bad of ['<<<<<<<','=======\n','>>>>>>>'])for(const p of required)assert.ok(!read(p).includes(bad),`merge marker: ${p}`);console.log('SMOKE PASS',VERSION,'SUBJECT SYNC + AREA EVALUATOR + MULTI-ACTIVITY EXCEL');