import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),pkg=JSON.parse(read('package.json')),VERSION=pkg.version;
assert.equal(VERSION,'3.7.1');const required=['index.html','evidence-fusion.js','student-workspace.js','analytics-dashboard.js','local-tools-admissions.js','teacher-ux.js','editor-live-inspector.js','student-record-suite-v36.js','record-writers-v36.js','student-portfolio-v37.js','demo-students-v37.js','ui-mode-v37.js','firebase-cloud.js','official-2026.js','sw.js','vercel.json','package.json','vendor/tailwind.js','vendor/xlsx.full.min.js','vendor/pdf.min.js','vendor/pdf.worker.min.js'];
for(const p of required)assert.ok(exists(p),`missing: ${p}`);assert.match(read('VERSION.txt'),/v3\.7\.1/);const index=read('index.html');assert.ok(index.includes('v3.7.1'));
for(const p of ['teacher-ux','student-record-suite-v36','record-writers-v36','demo-students-v37','ui-mode-v37','editor-live-inspector'])assert.ok(index.includes(`./${p}.js?v=3.7.1`),`cache-buster mismatch: ${p}`);
const ws=read('student-workspace.js'),portfolio=read('student-portfolio-v37.js'),demo=read('demo-students-v37.js'),ui=read('ui-mode-v37.js'),writers=read('record-writers-v36.js'),teacher=read('teacher-ux.js'),live=read('editor-live-inspector.js'),sw=read('sw.js');
assert.ok(ws.includes('behaviorDrafts')&&ws.includes('openStudentPortfolio37'),'student portfolio persistence/wiring missing');assert.ok(portfolio.includes('행동특성·종합의견')&&portfolio.includes('printStudentPortfolio37'),'portfolio features missing');
assert.ok(writers.includes('prefillRecordWriter36'),'demo-to-writer prefill missing');assert.ok(writers.includes("while(t&&B(t)>c.b)"),'byte-only trim missing');assert.ok(ui.includes('가상학생 3명 보기')&&!ui.includes('가상학생 12명 보기'),'beginner demo count mismatch');
globalThis.window={};globalThis.document={readyState:'loading',addEventListener:()=>{}};globalThis.setTimeout=()=>{};eval(demo);const D=window.__SM_DEMO_STUDENTS_371;assert.equal(D.length,3,'demo student count must be 3');
assert.deepEqual(D.map(x=>x.m),['건축공학과','국어국문학과','의예과']);for(const s of D){assert.equal(s.records.length,7,`${s.m} must have 7 records`);for(const r of s.records){const b=Buffer.byteLength(r.final,'utf8'),max=r.k==='behavior'?900:1500,min=r.k==='behavior'?840:1400;assert.ok(b>=min&&b<=max,`${s.m} ${r.k} byte density ${b}/${max}`)}}
for(const area of ['교과세특','자율·자치활동','동아리활동','진로활동','행동특성·종합의견'])assert.ok(writers.includes(area),`writer missing: ${area}`);
assert.ok(teacher.includes("const VERSION='3.7.1'")&&live.includes("const VERSION='3.7.1'"));assert.ok(sw.includes('seoteukmate-v371-')&&sw.includes("'./demo-students-v37.js'")&&sw.includes("'./ui-mode-v37.js'"));
for(const bad of ['<<<<<<<','=======\n','>>>>>>>'])for(const p of required)assert.ok(!read(p).includes(bad),`merge marker: ${p}`);console.log('SMOKE PASS',VERSION,'3 HIGH-DENSITY DEMOS + WRITER PREFILL');